ALTER TABLE users
  ADD COLUMN IF NOT EXISTS is_driver BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS car_make TEXT,
  ADD COLUMN IF NOT EXISTS car_model TEXT,
  ADD COLUMN IF NOT EXISTS car_color TEXT,
  ADD COLUMN IF NOT EXISTS car_plate_state TEXT,
  ADD COLUMN IF NOT EXISTS car_plate_number TEXT,
  ADD COLUMN IF NOT EXISTS car_description TEXT;
