ALTER TABLE trips
ADD COLUMN IF NOT EXISTS origin_label TEXT,
ADD COLUMN IF NOT EXISTS destination_label TEXT,
ADD COLUMN IF NOT EXISTS origin_latitude DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS origin_longitude DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS destination_latitude DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS destination_longitude DOUBLE PRECISION;
